### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by afga97** [snok/django-auth-adfs#132] opened 2021-01-19 12:38 UTC
Hi @JonasKs 

Sorry I had not seen the issue tracking documentation it only had the two lines above.

I share what the logger shows, thanks

**Comment by JonasKs** [comment] 2021-01-19 12:45
Hi,  
Could you share your `pip freeze` and `ADFS_CONFIG` in `settings.py`?  
Also, please verify that your set up in Azure is as described in the new [documentation](https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html).

You can remove your screenshot again. Thanks.

**Comment by afga97** [comment] 2021-01-19 12:54
client_id = 'fbfe0c74-3f94-4afa-b886-5a48e48ab64f'
cient_secret = '_lUhE4Nie4Q~~XSb5EtA__nQPEg46l0sSB'
tenant_id = '4ca4c661-83b5-4755-af79-c0c84db752f0'


AUTH_ADFS = {
    'LOGIN_EXEMPT_URLS': ['^$', '^admin', '^api'],
    'AUDIENCE': client_id,
    'CLIENT_ID': client_id,
    'CLIENT_SECRET': cient_secret,
    'CLAIM_MAPPING': {'first_name': 'given_name',
                      'last_name': 'family_name',
                      'email': 'upn'},
    'USERNAME_CLAIM': 'upn',
    'TENANT_ID': tenant_id,
    'RELYING_PARTY_ID': client_id,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(levelname)s %(asctime)s %(name)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django_auth_adfs': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

AUTHENTICATION_BACKENDS = (
    'django_auth_adfs.backend.AdfsAccessTokenBackend',
    'django_auth_adfs.backend.AdfsAuthCodeBackend'
)

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': ( 
        'django_auth_adfs.rest_framework.AdfsAccessTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
}


asgiref==3.3.1
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
cryptography==3.3.1
Django==3.1.5
django-auth-adfs==1.5.0
djangorestframework==3.12.2
idna==2.10
pycparser==2.20
PyJWT==2.0.1
pytz==2020.5
requests==2.25.1
six==1.15.0
sqlparse==0.4.1
urllib3==1.26.2

**Comment by JonasKs** [comment] 2021-01-19 13:05
How are you trying to access the site? Through DRF? 

Please remove all sensitive information from your post (secret key). You will have to re-create it now, as it's been publicly posted.

**Comment by afga97** [comment] 2021-01-19 13:07
Does it have anything to do with having created two separate applications?

Maybe you just need to create one and from the front-end claim tokens from the same app.

**Comment by afga97** [comment] 2021-01-19 13:10
> How are you trying to access the site? Through DRF?
> 
> Please remove all sensitive information from your post (secret key). You will have to re-create it now, as it's been publicly posted.

Enitendo, at the moment I am in testing, I wanted you to have all the information.

If I want to access through DRF

**Comment by JonasKs** [comment] 2021-01-19 14:09
There's currently no docs for setting up a consumer of the API in Azure, but it will be documented this week. I haven't done it personally, so if this does not help, I'd recommend waiting for the docs.  

Go to `App registrations` and find your frontend app registration. Go to `API permissions` -> `Add permission` -> in the top tab, select `APIs my organization use` -> Give it a permission. You'll get something like this in return: `api://1234-1234-1234-1234/read`. Use only `1234-1234-1234-1234/read` when fetching the token, without `api://`

**Comment by afga97** [comment] 2021-01-19 18:36
> There's currently no docs for setting up a consumer of the API in Azure, but it will be documented this week. I haven't done it personally, so if this does not help, I'd recommend waiting for the docs.
> 
> Go to `App registrations` and find your frontend app registration. Go to `API permissions` -> `Add permission` -> in the top tab, select `APIs my organization use` -> Give it a permission. You'll get something like this in return: `api://1234-1234-1234-1234/read`. Use only `1234-1234-1234-1234/read` when fetching the token, without `api://`
> 
> EDIT: You'll have to expose an API in your backend App registration to do the above.

I think waiting for the documentation, I have followed the steps but I do not know what I am failing.

This is the Front-End app registration with the permission of the associated back-end.

![image](https://user-images.githubusercontent.com/41203767/105077543-a95e0600-5a5a-11eb-9018-49f9bc280ea7.png)

This is the record of the api exposed in the backend.

![image](https://user-images.githubusercontent.com/41203767/105077931-3ef99580-5a5b-11eb-8f9b-1c46a5c24723.png)

Sorry for the inconvenience

**Comment by JonasKs** [comment] 2021-01-19 18:58
How does the token look of you paste it into `jwt.io`?

**Comment by afga97** [comment] 2021-01-19 19:18
> ¿Cómo se ve la ficha en la que la pegas `jwt.io`?

`
# Payload 
{
  "aud": "00000003-0000-0000-c000-000000000000",
  "iss": "https://sts.windows.net/4ca4c661-83b5-4755-af79-c0c84db752f0/",
  "iat": 1611080275,
  "nbf": 1611080275,
  "exp": 1611084175,
  "acct": 0,
  "acr": "1",
  "acrs": [
    "urn:user:registersecurityinfo",
    "urn:microsoft:req1",
    "urn:microsoft:req2",
    "urn:microsoft:req3",
    "c1",
    "c2",
    "c3",
    "c4",
    "c5",
    "c6",
    "c7",
    "c8",
    "c9",
    "c10",
    "c11",
    "c12",
    "c13",
    "c14",
    "c15",
    "c16",
    "c17",
    "c18",
    "c19",
    "c20",
    "c21",
    "c22",
    "c23",
    "c24",
    "c25"
  ],
  "aio": "E2JgYIhRn69rLNaQJ5gUELaR/cLWabtziy7vdmc+o1qbc8jrnwcA",
  "amr": [
    "pwd"
  ],
  "app_displayname": "my vuejs djangorest",
  "appid": "fbfe0c74-3f94-4afa-b886-5a48e48ab64f",
  "appidacr": "0",
  "family_name": "GIRALDO AGUDELO",
  "given_name": "ANDRES FELIPE",
  "idtyp": "user",
  "ipaddr": "190.248.54.98",
  "name": "ANDRES FELIPE GIRALDO AGUDELO",
  "oid": "afb69a46-f909-4e3c-9045-a87fb34e91bb",
  "onprem_sid": "S-1-5-21-1879080431-293223273-804419002-222519",
  "platf": "14",
  "puid": "10032000399A0A87",
  "rh": "0.AQYAYcakTLWDVUevecDITbdS8HQM_vuUP_pKuIZaSOSKtk8GAOc.",
  "scp": "openid profile email",
  "sub": "U_o-A8yjMDnZ3SWcpRVLON64B5YPW-vJLiJOfTV4oTY",
  "tenant_region_scope": "SA",
  "tid": "4ca4c661-83b5-4755-af79-c0c84db752f0",
  "unique_name": "agiraagu@emtelco.com.co",
  "upn": "agiraagu@emtelco.com.co",
  "uti": "XelHlnUT6ECnrzY8VUD6AQ",
  "ver": "1.0",
  "wids": [
    "b79fbf4d-3ef9-4689-8143-76b194e85509"
  ],
  "xms_st": {
    "sub": "pwHMIw6RNu0GIou0pWfY6kkwKx6avc1k3z20bljzXYQ"
  },
  "xms_tcdt": 1389726748
}
`

**Comment by afga97** [comment] 2021-01-21 20:04
@JonasKs 

Hello, did you find any inconsistencies?

**Comment by JonasKs** [comment] 2021-01-21 20:16
Hello, no, I have not been able to look at this. Which endpoint do you fetch the `access_token` from? The v1 or v2 endpoint?
As mentioned before I haven't used Azure AD my self, so it's hard for me to really give any specific pointers. I hope docs will come this weekend or early next week, but I won't promise anything.

**Comment by afga97** [comment] 2021-01-21 20:22
I was using acces_token v1 but also in a return of "id_token" which is v2, with neither of the two cases I have been able to give a solution.

It would be good if you could get a documentation, in advance thanks

**Comment by JonasKs** [comment] 2021-01-26 20:22
Hey @afga97 - PR #139 have docs for the frontend app. Could you check them out and see if they work for you?

**Comment by afga97** [comment] 2021-01-28 18:55
> Hey @afga97 - PR #139 have docs for the frontend app. Could you check them out and see if they work for you?

Hi @JonasKs  

I followed each of the steps but when sending the token the same error continued

**Comment by JonasKs** [comment] 2021-01-28 18:57
Then yeah, it must be because of how you're fetching the tokens from your frontend app that don't match the backend. (V1 vs v2?) 
It's very hard for me to troubleshoot this, unfortunately. I'm not a frontend developer, nor using Azure personally. 

I'll try to read up on it this weekend, but I can't promise anything.

**Comment by afga97** [comment] 2021-01-28 19:02
azure returns two tokens, one is version 1 and the other 2, I tried each one but the error persists, it is also the first time that I try and by following this document and not getting it, I don't know what might be looking wrong

**Comment by JonasKs** [comment] 2021-01-28 19:07
You should get an `access_token`, not an `id_token` (atleast in ADFS). 
Is there a checkbox to enable `access_token` in your implicit flow settings?

**Comment by afga97** [comment] 2021-01-28 19:40
![image](https://user-images.githubusercontent.com/41203767/106189682-9b089c00-6176-11eb-8566-584c4afe4f0b.png)

Yes, I only have access_token enabled but when I login with azure I get the following error:

- **response** login error ServerError: AADSTS700054: response_type 'id_token' is not enabled for the application.**

if I enable id_token this works but the response does not show access_token

**Comment by JonasKs** [comment] 2021-01-28 19:52
Can't you select enable both? 

Normally you get the ID token and then there's a silent fetch of the access token. Seems like you need to enable that step in your frontend. 

[Page 1](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-acquire-token?tabs=javascript#next-steps) docs, which leads to [page 2](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-call-api?tabs=javascript).

If you can't make this work, you need to manipulate your sign in URL. See [this link](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow#send-the-sign-in-request), which explains the `response_type` query parameter when redirecting to Azure. You can insert the `token` parameter here, and it _should_ return the access token.

**Comment by afga97** [comment] 2021-01-28 19:56
in the manifest I put the following key in True and the error disappears

**oauth2AllowIdTokenImplicitFlow: true**

exact, I must do what you say, try to acquire a silent token and get the access_token, I will validate and tell you, thank you.

**Comment by afga97** [comment] 2021-01-28 20:33
Sure yes, I am using MSAL.js

https://www.npmjs.com/package/msal

"msal": "^1.4.4"

Thanks

**Comment by afga97** [comment] 2021-01-28 21:24
> Good luck!
> 
> Which library do you use? I can try to read up on it in the weekend if you do not succeed. 😊

I tell you, I managed to acquire the silent token and this time I get the access_token, but when I send it to the backend I keep presenting the same error :(

1 error ->Signature verification failed

2 error -> Invalid issuer


![image](https://user-images.githubusercontent.com/41203767/106200430-f93c7b80-6184-11eb-9abb-ca1c1737b4d5.png)

**Comment by JonasKs** [comment] 2021-01-28 21:48
Can you try removing `api://`?

**Comment by afga97** [comment] 2021-01-28 21:57
Of course I removed api: // but I still don't authenticate: /

**Comment by JonasKs** [comment] 2021-01-28 22:18
Okay. Backend settings looks like this?:


```py

# Client secret is not public information. Should store it as an environment variable.

client_id = 'Your client id here'
cient_secret = 'Your client secret here'
tenant_id = 'Your tenant id here'


AUTH_ADFS = {
    'AUDIENCE': client_id,
    'CLIENT_ID': client_id,
    'CLIENT_SECRET': cient_secret,
    'CLAIM_MAPPING': {'first_name': 'given_name',
                      'last_name': 'family_name',
                      'email': 'upn'},
    'GROUPS_CLAIM': 'roles',
    'MIRROR_GROUPS': True,
    'USERNAME_CLAIM': 'upn',
    'TENANT_ID': tenant_id,
    'RELYING_PARTY_ID': client_id,
}

```

If yes, I'll have to look into it this weekend and see if I can test my self. Maybe try the `msal-browser` version, seems like that's what our Azure guys uses.

**Comment by afga97** [comment] 2021-01-28 22:21
Yes, I have my setup that way.

The library that I started using was msal-browser and I decided to try msal.js, I thought I had problems with the library.

I would appreciate if you could take a test

**Comment by JonasKs** [comment] 2021-01-31 15:41
Hi. Sorry, I have not been able to do this. 

Could you read through this, and ensure you're using `v1` tokens?   
https://github.com/nicolgit/nicolgit.github.io/blob/master/_posts/2019-05-21-AzureAD-Endopoint-V1-vs-V2-comparison.md


Seems like you're supposed to use ADALL not MSAL.

**Comment by JonasKs** [comment] 2021-01-31 15:46
Wait, your URL in your frontend has `<clientID>/read`. What's your scope name? `read`? If it's not, please change that to your scope.

**Comment by afga97** [comment] 2021-01-31 16:46
If that's the scope, follow the documentation you shared with me

**Comment by JonasKs** [comment] 2021-01-31 17:10
Did it work or are you commenting to complain on something? The docs tells you to name it `read` and adds read to the url. If you can't get something to work, you follow the docs exactly as they are written and tune it to your needs after that.

**Comment by afga97** [comment] 2021-02-01 12:45
Sorry, I don't write English very well, I wasn't complaining.

It did not work for me, I did all the steps in the documentation but did not achieve the goal.

**Comment by afga97** [comment] 2021-02-01 13:43
Is there something else that I can try, what do you recommend?

I would like to achieve it

**Comment by JonasKs** [comment] 2021-02-01 13:45
I'm not sure what's going wrong on your end, honestly. I'll try to set it up manually my self by following the docs. If I can fetch a token through Azure AD with Python and authenticate with it.

**Comment by afga97** [comment] 2021-02-01 13:51
Thank you very much @JonasKs it would be great if it works

**Comment by JonasKs** [comment] 2021-02-01 19:17
@afga97 , can you try what I said here (if it says `2`): 

https://github.com/snok/django-auth-adfs/issues/143#issuecomment-771092489

**Comment by JonasKs** [comment] 2021-02-01 19:32
Can you also please try to do it all over again? Docs have been updated now: https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html

I'm unable to reproduce, but your `aud` in the decoded JWT is `00000003-0000-0000-c000-000000000000`, which I find weird. It should be the ClientID. Maybe google `"00000003-0000-0000-c000-000000000000"` and see if you find something?

**Comment by JonasKs** [comment] 2021-02-01 19:38
Maybe triple check this: https://github.com/MicrosoftDocs/azure-docs/issues/37280#issuecomment-523500771 ? 

I'm sorry mate, I have really no idea why this is happening for you. Does login through Django work, it's only the API from your Vue app that fails?

In that case, maybe raise an issue for the javascript library you use? :/

**Comment by JonasKs** [comment] 2021-02-01 19:47
Do you use `microsoft graph`? Seems like `00000003-0000-0000-c000-000000000000` is for graph. Are you sure you send the correct token to the API?

**Comment by afga97** [comment] 2021-02-01 20:02
If that is very weird, azure issues an accessToken that the aud is as you say, it also issues an idToken that has aud with the client id, I send it but the same thing happens to me so I don't know very well what happens

I think it's a library issue, sending it with MSAL.js library and getting the silent token acces_token contains aud with the backend app id_app.

but he also sent it and he can't authenticate

**Comment by afga97** [comment] 2021-02-01 20:07
the backend no longer gets an error when verifying the signature, but says the following error

jwt.exceptions.InvalidIssuerError: Invalid issuer

**Comment by JonasKs** [comment] 2021-02-01 20:10
I'm sorry, I don't understand what you mean. :disappointed: 


Please e-mail me:
* `access_token` decoded at https://jwt.ms
* Manifests for frontend **and** backend:
![bilde](https://user-images.githubusercontent.com/5310116/106512426-e225c280-64d1-11eb-9961-5e0babb2be67.png)

**Comment by afga97** [comment] 2021-02-01 20:24
I already sent you the email, tell me if you received it and you can achieve something, I would appreciate it

**Comment by JonasKs** [comment] 2021-02-01 20:28
Can you log in through Django and it works?

**Comment by afga97** [comment] 2021-02-01 20:40
when trying in django I get the following message,

No authorization code was provided.

**Comment by JonasKs** [comment] 2021-02-01 22:44
We spoke over E-mail and solved it. It was some missing settings.

I'll go through docs and clean up a bit ASAP. Closing issue ☺️

**Closed** 2021-02-01 22:44 UTC
Labels: documentation, question

**Comment by matthewjedelman** [comment] 2021-02-23 01:06
> We spoke over E-mail and solved it. It was some missing settings.
> 
> I'll go through docs and clean up a bit ASAP. Closing issue ☺️


Do you happen to remember what settings it was that was missing/wrong? I'm running into a similar albeit slightly different problem. I was able to get the library working with DRF though the webbrowser, but if I try to access it via methods other then the browser it fails. I've tried using "Az rest", The python msal library, etc. The only thing that works is via logging in through the browser to get the access token. I'm going to re-run through the setup again to see if I missed something, but was hoping you remember what was wrong with the OP. I noticed in the guide pictures that the microsoft graph api is listed in the api permissions page, which is where I'm also getting the aud of microsoft graph api instead of the client id. 

Thanks

**Comment by JonasKs** [comment] 2021-02-23 07:34
He forgot to put redirect URL. Send me your entire settings.py on email and I can look over if you'd like.

**Comment by matthewjedelman** [comment] 2021-02-23 18:53
Thanks for your response. I went through setup all over again and while I always had it working through the web browser, using a client application such the 'az cli' was not working and I think it was because the group claim was not being passed in the token even when specificing the correct client id (resource) at the command line. Instead it was grabbing the data from the microsoft graph api. Again I don't completely understand how this works, but that's what seemed to be the difference between now and when it wasn't working!

Thanks for a great library!

> He forgot to put redirect URL. Send me your entire settings.py on email and I can look over if you'd like.

**Comment by liloy292** [comment] 2022-08-31 03:08
Hi @JonasKs 

Why do we have to set up 2 apps in Azure for frontend and backend, I am running into this issue and I only use 1 app.

**Comment by JonasKs** [comment] 2022-08-31 04:31
You don't unless you use DRF. Then you set up a web app

**Comment by liloy292** [comment] 2022-08-31 05:42
> You don't unless you use DRF. Then you set up a web app

Hi @JonasKs, 

thanks for your reply, may I know why this is needed, is there any doc? 

Thanks, the library is fantastic.

**Comment by liloy292** [comment] 2022-08-31 06:06
Hi @JonasKs 

I must say that it works like a magic, could you kindly explain why 2 apps are needed here if we want to integrate with DRF?

Thank you so much.

**Comment by JonasKs** [comment] 2022-08-31 08:47
Essentially because of when you have an API, you authenticate to it by using Bearer tokens instead of sessions and cookies.

In other words:

**Django web app**:
* You authenticate and get redirected with a authentication code
* The backend itself (django-auth-adfs) takes this code and exchanges it with a access token from Azure
* The backend verifies the token

**API flow**:
* The user authenticates and fetches the access token by himself (this could be through a react frontend or a script, not connected to the backend directly)
* The user sends an API request with the token as a header, e.g. `Bearer ey....` in the request
* The backend verifies the token

So, as we can see, the difference is _who_ is fetching the token. For API usage, it is another app, and therefor needs its own app registration.

If you want more in depth, there's documentation [here](https://django-auth-adfs.readthedocs.io/en/latest/oauth2_explained.html).

**Comment by liloy292** [comment] 2022-08-31 09:10
You are so kind, thanks for the detailed response.

**Comment by liloy292** [comment] 2022-08-31 09:38
Hi @JonasKs 
is this mandatory? let me take an example,  can I use 1 single app to do authentication at the front end to get the token, and then verify the token at the backend by using the same app?

**Comment by liloy292** [comment] 2022-08-31 10:44
Hi @JonasKs 

I just did an experiment, when my scope filled only with the permission I created, it works well the **aud** field in my token is just my client_id and the verification works well,  but if I apply for the graph permission along with the permission I created, the aud changed to '00000003-0000-0000-c000-000000000000' then the token verification failed.  it's quite weird. 

Thanks 
Xiang

**Comment by liloy292** [comment] 2022-09-01 06:37
I configured graph permission in my apps and applied a token then, but this token seems can not be verified by django-auth-adfs

**Comment by JonasKs** [comment] 2022-09-01 07:28
When you request the Graph scope, you get a token _for_ Graph. If you want to use Graph, you must use the OBO flow.

I've written `FastAPI-Azure-Auth`, a library that only focuses on Azure AD, and is a bit more documented and modern. I'd recommend you to read the docs [here](https://intility.github.io/fastapi-azure-auth/usage-and-faq/graph_usage) on OBO flow.

**Comment by Ekfrancisco** [comment] 2022-10-23 01:13
Hello!, So im having the same issue with my client server authentication flow, its throwing me the following error:

`django_auth_adfs Error decoding signature: Signature verification failed`

I compared the acces token claims to the **AUTH_ADFS** configuration, and they seem to be allright

![image](https://user-images.githubusercontent.com/38672375/197368274-cc31ab68-429f-4ec5-bdf4-efb3eeff6d50.png)

this is my **AUTH_ADFS** configuration

![image](https://user-images.githubusercontent.com/38672375/197368331-578d4b1c-864c-4af4-b204-2906a8ed8a08.png)

the rest of the configs are the same as the tutorial: https://django-auth-adfs.readthedocs.io/en/latest/rest_framework.html

Just by comparing the JWT with the configuration, and double checking that the client has permision to acces the scope api.read of the API i belive it should be working, its there anything im missing?, thank you in advance

**Comment by tim-schilling** [comment] 2022-10-24 13:02
That error is because the JWT isn't being decoded properly. Are you sure you have the correct secret key? Additionally, see the troubleshooting part of the docs: https://django-auth-adfs.readthedocs.io/en/latest/troubleshooting.html

**Comment by Ekfrancisco** [comment] 2022-10-25 03:30
Hello tim, Thank you for answering.

So as you said the problem was with the decoding of the signature. This is the signature verification in jwt.io

![image](https://user-images.githubusercontent.com/38672375/197674045-cc493777-af57-4dac-9a1f-0515511b4de2.png)

After reading some more, it seems that the acces token has a special signature, since every time the token has the "nonce" field, the token needs a special processing for the passing of it, so i will check how to decode the special format
