### ISSUE TITLE
Redirect URI changes from https to http

### ISSUE THREAD

**Issue by HiralBarot1512** [snok/django-auth-adfs#303] opened 2023-09-27 05:43 UTC
I followed this tutorial https://django-auth-adfs.readthedocs.io/en/latest/azure_ad_config_guide.html#step-3-register-and-configure-an-azure-ad-frontend-application and everything is set as per that, but when i try to login i am seeing URI mismatch error and cause for that is i can see http instead of https in redirect_uri. I also tried passing 
AUTH_ADFS = {
     ....
     'REDIR_URI': 'https://abc.com'
     ...
}
but its not working even after this too. I tried setting up all these one by one but no luck.
 SECURE_SSL_REDIRECT = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
Any help would be appreciated.

Thanks

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/snok) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/snok/django-auth-adfs/issues/303">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/snok/django-auth-adfs/issues/303/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/snok/django-auth-adfs/issues/303/pledge.svg">
</picture>
</a>

**Comment by tim-schilling** [comment] 2023-09-27 13:37
@HiralBarot1512 can you include the full error and the logs? It's also a good idea for you to debug the application and library to see why exactly that URI mismatch error is being raised. You can do so by dropping a `breakpoint()`, using an IDE's debugger or putting a number of print statements in the code.

**Comment by tim-schilling** [comment] 2024-09-30 14:55
Hi @alex-atkins, no there isn't. If you'd like to help move things along, can you please go through the flow and include the full error and logs as I asked Hiral to do here: https://github.com/snok/django-auth-adfs/issues/303#issuecomment-1737415353

If you can identify where and why things aren't lining up or create a minimal reproducible example, that can help move everyone forward.

**Comment by tim-schilling** [comment] 2024-10-01 15:00
> The redirect URI 'http://mysite.com/oauth2/callback' specified in the request 

Have you confirmed that's in the payload that's being sent to Azure?

**Comment by alex-atkins** [comment] 2024-10-01 15:57
@tim-schilling Looks like this was a classic case of user error. I'd been doing something weird with how I was loading my environment settings and for some reason it worked on WSGI, but with ASGI it didn't.  Essentially the SSL settings above were not actually being set.  My apologies! Thank you all for making an awesome package 💯

**Comment by tim-schilling** [comment] 2024-10-01 19:54
Glad you found your solution! Thank you for the kind words and patience.

Closing the issue for staleness

**Closed by tim-schilling** 2024-10-01 19:54 UTC
Labels: help wanted
